### ISSUE TITLE
Error in example : Failed to set node start: 'name'

### ISSUE THREAD

**Issue by SavinienBarbotaud** [pipecat-ai/pipecat-flows#136]
Hello ! 

Trying to use and understand pipecat-flows. I decided to go on the first example (food ordering), and got this error while running pipecat : 

**pipecat_flows.exceptions.FlowInitializationError: Failed to initialize flow: Failed to set node start: 'name'**

My flow config look exactly the same as in the example : 

```
"nodes": {
        "start": {
            "role_messages": [
                {
                    "role": "system",
                    "content": "You are an order-taking assistant. You must ALWAYS use the available functions to progress the conversation. This is a phone conversation and your responses will be converted to audio. Keep the conversation friendly, casual, and polite. Avoid outputting special characters and emojis.",
                }
            ],
            "task_messages": [
                {
                    "role": "system",
                    "content": "For this step, ask the user if they want pizza or sushi, and wait for them to use a function to choose. Start off by greeting them. Be friendly and casual; you're taking an order for food over the phone.",
                }
            ],
            "functions": [
                {
                    "type": "function",
                    "function": {
                        "name": "choose_pizza",
                        "description": "User wants to order pizza. Let's get that order started.",
                        "parameters": {"type": "object", "properties": {}},
                        "transition_to": "choose_pizza",
                    },
                },
                {
                    "type": "function",
                    "function": {
                        "name": "choose_sushi",
                        "description": "User wants to order sushi. Let's get that order started.",
                        "parameters": {"type": "object", "properties": {}},
                        "transition_to": "choose_sushi",
                    },
                },
            ],
        },
        ....
}
```

Already try 
```
"nodes": {
        "start": {
                 "name": "start",
          ....
```
But i had to be honest, I really don't know where this error come from.
Thanks for your time.

**Comment by SavinienBarbotaud** [comment]
I change **start** functions to  : 

```
"functions": [
                {
                    "type": "function",
                    "name": "choose_pizza",
                    "function": {
                        "description": "User wants to order pizza. Let's get that order started.",
                        "parameters": {"type": "object", "properties": {}},
                        "transition_to": "choose_pizza",
                    },
                },
                {
                    "type": "function",
                    "name": "choose_sushi",
                    "function": {
                        "description": "User wants to order sushi. Let's get that order started.",
                        "parameters": {"type": "object", "properties": {}},
                        "transition_to": "choose_sushi",
                    },
                },
            ],
```
With no more errors. But i don't know why no error a raise in other nodes

**Comment by markbackman** [comment]
Other times this error has been reported, the root cause has been that the function calling format was incorrect. Which LLM are you using?

**Comment by markbackman** [comment]
Please try the FlowsFunctionSchema:
```
@dataclass
class FlowsFunctionSchema:
    """Function schema with Flows-specific properties.

    This class provides similar functionality to FunctionSchema with additional
    fields for Pipecat Flows integration.

    Attributes:
        name: Name of the function
        description: Description of the function
        properties: Dictionary defining properties types and descriptions
        required: List of required parameters
        handler: Function handler to process the function call
        transition_to: Target node to transition to after function execution
        transition_callback: Callback function for dynamic transitions
    """

    name: str
    description: str
    properties: Dict[str, Any]
    required: List[str]
    handler: Optional[FunctionHandler] = None
    transition_to: Optional[str] = None
    transition_callback: Optional[Callable] = None
```

Dynamic Flows example:
```
    weather_function = FunctionSchema(
        name="get_weather",
        description="Get the current weather",
        properties={
            "location": {
                "type": "string",
                "description": "The city and state, e.g. San Francisco, CA",
            },
            "format": {
                "type": "string",
                "enum": ["celsius", "fahrenheit"],
                "description": "The temperature unit to use. Infer this from the user's location.",
            },
        },
        required=["location", "format"],
        handler=weather_handler,
        transition_callback=my_weather_callback,
    )
```
